export const CryptoData = {
  id: "",
  symbol: "",
  name: "",
  image: "",
  current_price: 0,
  market_cap: 0,
  market_cap_rank: 0,
  total_volume: 0,
  price_change_percentage_24h: 0,
  market_cap_change_percentage_24h: 0,
  circulating_supply: 0,
  total_supply: 0,
  max_supply: null,
  ath: 0,
  ath_change_percentage: 0,
};
